#!/bin/tcsh
#
#PBS -N proc_geos_rean
#PBS -A P19010000
#PBS -l select=1:ncpus=1:mem=100GB
#PBS -l walltime=04:00:00
#PBS -q casper
#PBS -j oe

echo "Begin Prepare-Submit Job"

#module purge
#module load conda
#module load ncarenv
#module load intel
#module list

#conda activate npl

date
echo "Begin GEOS Processing Job"

cd $PBS_O_WORKDIR

# --- Determine time-stamp/file-ID string ---
setenv LID "`date +%y%m%d-%H%M%S`"

./process_geos.py >&! /glade/scratch/fvitt/GEOS/proc_geos.log.$LID

echo "qsub -a 0500 -V process_geos_batch"
qsub -a 0500 -V process_geos_batch

echo "End GEOS Processing Job"
date

exit 0
